### ISSUE TITLE
Invalid encoded code

### ISSUE THREAD

**Issue by sidharthv96** [jihchi/mermaid.ink#272] opened 2023-11-20 11:05 UTC
https://github.com/mermaid-js/mermaid-live-editor/issues/1346 raised here, but seems like an issue with mermaid.ink

**Comment by jihchi** [comment] 2023-11-20 13:51
Thank you @sidharthv96 for forwarding the issue 🙏 , I'll look into the issue.

**Comment by jihchi** [comment] 2023-11-20 18:47
The issue is fixed in [v8.1.0](https://github.com/jihchi/mermaid.ink/releases/tag/v8.1.0).

**Closed by jihchi** 2023-11-20 18:47 UTC
